/**
 * Colunas reais do Postgres, copiadas do banco.
 *
 * Existe porque o mapeamento continuou mandando `field_cost` depois que a
 * coluna saiu do schema. O erro só apareceu na importação, no meio do lote —
 * e teria aparecido de novo em qualquer coluna que a gente mexesse.
 *
 * Para atualizar depois de uma migração:
 *
 *   select table_name, string_agg(column_name, ',' order by column_name)
 *   from information_schema.columns
 *   where table_schema = 'public'
 *   group by table_name order by table_name;
 */
export const COLUNAS_DO_POSTGRES: Record<string, string[]> = {
  attendance: [
    'created_at', 'id', 'match_id', 'player_id', 'responded_at', 'status',
    'team_id', 'updated_at', 'user_id',
  ],
  expense_categories: ['archived_at', 'created_at', 'id', 'label', 'team_id', 'updated_at'],
  expense_shares: [
    'amount_cents', 'created_at', 'expense_id', 'player_id', 'settled_at', 'updated_at',
  ],
  expenses: [
    'category_id', 'created_at', 'created_by', 'date', 'deleted_at', 'description',
    'extra_shares_count', 'id', 'match_id', 'paid_by_player_id', 'split_mode',
    'team_id', 'total_amount_cents', 'updated_at',
  ],
  lineups: [
    'bench_player_ids', 'created_at', 'formation_key', 'id', 'match_id', 'starters',
    'team_id', 'updated_at',
  ],
  match_diary_entries: [
    'author_name', 'author_user_id', 'content', 'created_at', 'emoji', 'id', 'match_id',
    'mentioned_player_ids', 'mood', 'pinned', 'team_id', 'title', 'updated_at', 'visibility',
  ],
  match_field_costs: [
    'amount_per_player_cents', 'created_at', 'match_id', 'note', 'paid_guest_count',
    'pix_key', 'responsible_name', 'split_count', 'total_amount_cents', 'updated_at',
    'updated_by_user_id',
  ],
  match_field_participants: ['created_at', 'match_id', 'player_id', 'role', 'updated_at'],
  match_stats: [
    'assists', 'created_at', 'goals', 'id', 'match_id', 'notes', 'played', 'player_id',
    'red_cards', 'started', 'team_id', 'updated_at', 'yellow_cards',
  ],
  matches: [
    'created_at', 'created_by', 'date', 'deleted_at', 'deleted_by', 'finished_at', 'id',
    'line_players_count', 'location_url', 'manual_mvp_player_id', 'manual_mvp_selected_at',
    'manual_mvp_selected_by', 'match_type', 'mvp_total_votes', 'mvp_winner_player_ids',
    'notes', 'opponent_logo_url', 'opponent_name', 'opponent_source', 'opponent_team_id',
    'opponent_team_logo_url', 'opponent_team_name', 'scoreboard', 'season_id', 'status',
    'team_id', 'time', 'updated_at', 'venue',
  ],
  mvp_votes: [
    'created_at', 'id', 'match_id', 'target_player_id', 'team_id', 'updated_at',
    'voter_player_id',
  ],
  notifications: [
    'actor_user_id', 'created_at', 'entry_id', 'id', 'match_id', 'message', 'player_id',
    'read_by_user_ids', 'target_user_id', 'team_id', 'title', 'type', 'updated_at',
  ],
  player_ratings: [
    'created_at', 'criteria_scores', 'criteria_snapshot', 'id', 'legacy_criteria',
    'match_id', 'overall', 'rater_player_id', 'target_player_id', 'team_id', 'updated_at',
  ],
  players: [
    'allow_self_edit_jersey_number', 'bio', 'celebration_video_url', 'created_at',
    'deleted_at', 'dominant_foot', 'fee_exemption', 'full_name', 'id', 'intro_video_url',
    'jersey_number', 'linked_email', 'linked_user_id', 'manual_stats', 'nickname',
    'photo_url', 'preferred_position', 'presentation_video_url', 'primary_position',
    'secondary_positions', 'status', 'team_id', 'updated_at',
  ],
  rating_criteria: [
    'active', 'created_at', 'description', 'id', 'label', 'order', 'team_id', 'type',
    'updated_at', 'weight',
  ],
  seasons: [
    'created_at', 'end_date', 'id', 'name', 'start_date', 'status', 'team_id',
    'updated_at', 'year',
  ],
  team_members: [
    'can_manage_players', 'can_manage_team', 'created_at', 'id', 'invite_code_used',
    'joined_at', 'player_id', 'roles', 'status', 'team_id', 'updated_at', 'user_id',
  ],
  teams: [
    'accent_color', 'active_season_id', 'admin_user_id', 'allow_friendly_contact',
    'banner_url', 'city', 'coach_name', 'contact_name', 'contact_phone', 'contact_whatsapp',
    'created_at', 'default_match_cost_cents', 'description', 'home_field_name', 'id',
    'invite_code', 'invite_code_updated_at', 'is_public', 'logo_url', 'name',
    'neighborhood', 'presentation_video_url', 'primary_color', 'public_description',
    'public_roster_enabled', 'secondary_color', 'slug', 'state', 'updated_at',
  ],
  users: [
    'active_team_id', 'app_role', 'avatar_url', 'created_at', 'display_name', 'email',
    'id', 'notification_tokens', 'updated_at',
  ],
};

/**
 * Documento do Firestore com todo campo que já apareceu no banco.
 *
 * Um documento por coleção seria mais realista, mas menos útil: aqui o objetivo
 * é forçar cada mapeador a emitir o máximo de colunas que ele consegue, para a
 * comparação com o schema pegar qualquer sobra.
 */
export const DOCUMENTO_COMPLETO: Record<string, unknown> = {
  id: 'doc-1',
  teamId: 'time-1',
  matchId: 'partida-1',
  playerId: 'jogador-1',
  userId: 'usuario-1',
  categoryId: 'categoria-1',
  seasonId: 'temporada-1',
  email: 'pessoa@exemplo.com',
  displayName: 'Pessoa',
  appRole: 'player',
  activeTeamId: 'time-1',
  avatarUrl: 'https://exemplo/av.png',
  notificationTokens: ['t1'],
  name: 'Nome',
  slug: 'nome',
  logoUrl: 'https://exemplo/logo.png',
  bannerUrl: 'https://exemplo/banner.png',
  presentationVideoUrl: 'https://exemplo/v.mp4',
  isPublic: true,
  city: 'Cidade',
  state: 'ST',
  neighborhood: 'Bairro',
  homeFieldName: 'Campo',
  contactName: 'Contato',
  contactPhone: '000',
  contactWhatsapp: '000',
  publicDescription: 'desc',
  allowFriendlyContact: true,
  publicRosterEnabled: true,
  primaryColor: '#000000',
  secondaryColor: '#FFFFFF',
  accentColor: '#FF0000',
  description: 'desc',
  inviteCode: 'CODIGO',
  inviteCodeUpdatedAt: '2026-08-18T12:00:00.000Z',
  coachName: 'Tecnico',
  adminUserId: 'usuario-1',
  defaultMatchCostCents: 1000,
  year: 2026,
  startDate: '2026-01-01',
  endDate: '2026-12-31',
  linkedUserId: 'usuario-1',
  linkedEmail: 'pessoa@exemplo.com',
  fullName: 'Nome Completo',
  nickname: 'Apelido',
  photoUrl: 'https://exemplo/foto.png',
  introVideoUrl: 'https://exemplo/i.mp4',
  celebrationVideoUrl: 'https://exemplo/c.mp4',
  jerseyNumber: 10,
  primaryPosition: 'midfielder',
  secondaryPositions: ['striker'],
  preferredPosition: 'winger',
  dominantFoot: 'right',
  status: 'active',
  bio: 'bio',
  allowSelfEditJerseyNumber: true,
  manualStats: { goals: 1 },
  feeExemption: { mode: 'always' },
  deletedAt: null,
  roles: ['player'],
  inviteCodeUsed: 'CODIGO',
  canManageTeam: false,
  canManagePlayers: false,
  joinedAt: '2026-08-18T12:00:00.000Z',
  label: 'Rotulo',
  type: 'positive',
  weight: 1,
  active: true,
  order: 0,
  date: '2026-08-18',
  time: '20:00',
  venue: 'Local',
  locationUrl: 'https://maps/x',
  opponentName: 'Adversario',
  opponentLogoUrl: 'https://exemplo/adv.png',
  opponentTeamId: 'time-2',
  opponentTeamName: 'Time 2',
  opponentTeamLogoUrl: 'https://exemplo/t2.png',
  opponentSource: 'manual',
  linePlayersCount: 11,
  matchType: 'society',
  notes: 'obs',
  createdBy: 'usuario-1',
  scoreboard: { team: 2, opponent: 1, result: 'win' },
  fieldCost: { totalAmount: 185, splitCount: 13, amountPerPlayer: 14.23, note: null },
  fieldPayment: {
    payerPlayerIds: ['jogador-1'],
    exemptPlayerIds: ['jogador-2'],
    pixKey: 'chave',
    responsibleName: 'Resp',
    paidGuestCount: 1,
    updatedByUserId: 'usuario-1',
  },
  finishedAt: '2026-08-18T22:00:00.000Z',
  mvpWinnerPlayerIds: ['jogador-1'],
  mvpTotalVotes: 3,
  manualMvpPlayerId: 'jogador-1',
  manualMvpSelectedBy: 'usuario-1',
  manualMvpSelectedAt: '2026-08-18T23:00:00.000Z',
  deletedBy: null,
  formationKey: '4-3-3',
  starters: [{ playerId: 'jogador-1', x: 1, y: 2, zone: 'attack' }],
  benchPlayerIds: ['jogador-2'],
  respondedAt: '2026-08-18T12:00:00.000Z',
  played: true,
  started: true,
  goals: 1,
  assists: 1,
  yellowCards: 0,
  redCards: 0,
  voterPlayerId: 'jogador-1',
  targetPlayerId: 'jogador-2',
  raterPlayerId: 'jogador-1',
  criteriaScores: { qualidade: 8 },
  criteriaSnapshot: { qualidade: { criterionId: 'qualidade' } },
  criteria: { qualidade: 8 },
  overall: 8,
  authorUserId: 'usuario-1',
  authorName: 'Autor',
  title: 'Titulo',
  content: 'Conteudo',
  mentionedPlayerIds: ['jogador-1'],
  visibility: 'team',
  pinned: false,
  mood: 'funny',
  emoji: '⚽',
  message: 'Mensagem',
  entryId: 'entrada-1',
  actorUserId: 'usuario-1',
  targetUserId: 'usuario-1',
  readByUserIds: ['usuario-1'],
  archivedAt: null,
  totalAmountCents: 1000,
  paidByPlayerId: 'jogador-1',
  splitMode: 'equal',
  participantPlayerIds: ['jogador-1', 'jogador-2'],
  extraSharesCount: 0,
  manualSharesCents: { 'jogador-1': 500 },
  settledPlayerIds: ['jogador-1'],
  createdAt: '2026-08-18T12:00:00.000Z',
  updatedAt: '2026-08-18T12:00:00.000Z',
};
